_wandb:
    value:
        cli_version: 0.22.1
        e:
            2m4csb6yv7eeje7a78t7gyx473goul1c:
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1001349181440"
                        used: "352936370176"
                email: wjm0423@naver.com
                executable: C:\Users\WJM\anaconda3\envs\link_dl\python.exe
                git:
                    commit: 9a3456f647dbd98105bfde25bd379f9129ba2e89
                    remote: https://github.com/linklab/link_dl.git
                host: BOOK-8H5OMEL4QJ
                memory:
                    total: "33898278912"
                os: Windows-11-10.0.26100-SP0
                program: _04_your_code/homework2.ipynb
                python: CPython 3.13.5
                root: C:\Users\WJM\git\link_dl\_04_your_code
                startedAt: "2025-10-17T10:00:44.213320Z"
                writerId: 2m4csb6yv7eeje7a78t7gyx473goul1c
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.13.5
            "5": 0.22.1
            "8":
                - 1
                - 3
            "12": 0.22.1
            "13": windows-amd64
activation_fn:
    value: ReLU
batch_size:
    value: 64
epochs:
    value: 200
learning_rate:
    value: 0.001
n_hidden_unit_list:
    value:
        - 32
        - 16
